export const ShopList = [
  {
    id: 1,
    name: "Shop 1",
    products: [
      { id: 1, name: "Product 1", price: 10, quantity: 1, store: "Shop 1" },
      { id: 2, name: "Product 2", price: 15, quantity: 1, store: "Shop 1" },
      { id: 3, name: "Product 3", price: 20, quantity: 1, store: "Shop 1" },
      { id: 4, name: "Product 4", price: 25, quantity: 1, store: "Shop 1" },
      { id: 5, name: "Product 5", price: 30, quantity: 1, store: "Shop 1" },
      { id: 6, name: "Product 6", price: 35, quantity: 1, store: "Shop 1" },
      { id: 7, name: "Product 7", price: 40, quantity: 1, store: "Shop 1" },
      { id: 8, name: "Product 8", price: 45, quantity: 1, store: "Shop 1" },
      { id: 9, name: "Product 9", price: 50, quantity: 1, store: "Shop 1" },
      { id: 10, name: "Product 10", price: 55, quantity: 1, store: "Shop 1" },
    ],
  },
  {
    id: 2,
    name: "Shop 2",
    products: [
      { id: 11, name: "Product 11", price: 10, quantity: 1, store: "Shop 2" },
      { id: 12, name: "Product 12", price: 15, quantity: 1, store: "Shop 2" },
      { id: 13, name: "Product 13", price: 20, quantity: 1, store: "Shop 2" },
      { id: 14, name: "Product 14", price: 25, quantity: 1, store: "Shop 2" },
      { id: 15, name: "Product 15", price: 30, quantity: 1, store: "Shop 2" },
      { id: 16, name: "Product 16", price: 35, quantity: 1, store: "Shop 2" },
      { id: 17, name: "Product 17", price: 40, quantity: 1, store: "Shop 2" },
      { id: 18, name: "Product 18", price: 45, quantity: 1, store: "Shop 2" },
      { id: 19, name: "Product 19", price: 50, quantity: 1, store: "Shop 2" },
      { id: 20, name: "Product 20", price: 55, quantity: 1, store: "Shop 2" },
    ],
  },
  {
    id: 3,
    name: "Shop 3",
    products: [
      { id: 21, name: "Product 21", price: 10, quantity: 1, store: "Shop 3" },
      { id: 22, name: "Product 22", price: 15, quantity: 1, store: "Shop 3" },
      { id: 23, name: "Product 23", price: 20, quantity: 1, store: "Shop 3" },
      { id: 24, name: "Product 24", price: 25, quantity: 1, store: "Shop 3" },
      { id: 25, name: "Product 25", price: 30, quantity: 1, store: "Shop 3" },
      { id: 26, name: "Product 26", price: 35, quantity: 1, store: "Shop 3" },
      { id: 27, name: "Product 27", price: 40, quantity: 1, store: "Shop 3" },
      { id: 28, name: "Product 28", price: 45, quantity: 1, store: "Shop 3" },
      { id: 29, name: "Product 29", price: 50, quantity: 1, store: "Shop 3" },
      { id: 20, name: "Product 20", price: 55, quantity: 1, store: "Shop 3" },
    ],
  },
  {
    id: 4,
    name: "Shop 4",
    products: [
      { id: 31, name: "Product 31", price: 10, quantity: 1, store: "Shop 4" },
      { id: 32, name: "Product 32", price: 15, quantity: 1, store: "Shop 4" },
      { id: 33, name: "Product 33", price: 20, quantity: 1, store: "Shop 4" },
      { id: 34, name: "Product 34", price: 25, quantity: 1, store: "Shop 4" },
      { id: 35, name: "Product 35", price: 30, quantity: 1, store: "Shop 4" },
      { id: 36, name: "Product 36", price: 35, quantity: 1, store: "Shop 4" },
      { id: 37, name: "Product 37", price: 40, quantity: 1, store: "Shop 4" },
      { id: 38, name: "Product 38", price: 45, quantity: 1, store: "Shop 4" },
      { id: 39, name: "Product 39", price: 50, quantity: 1, store: "Shop 4" },
      { id: 30, name: "Product 30", price: 55, quantity: 1, store: "Shop 4" },
    ],
  },
  {
    id: 5,
    name: "Shop 5",
    products: [
      { id: 41, name: "Product 41", price: 10, quantity: 1, store: "Shop 5" },
      { id: 42, name: "Product 42", price: 15, quantity: 1, store: "Shop 5" },
      { id: 43, name: "Product 43", price: 20, quantity: 1, store: "Shop 5" },
      { id: 44, name: "Product 44", price: 25, quantity: 1, store: "Shop 5" },
      { id: 45, name: "Product 45", price: 30, quantity: 1, store: "Shop 5" },
      { id: 46, name: "Product 46", price: 35, quantity: 1, store: "Shop 5" },
      { id: 47, name: "Product 47", price: 40, quantity: 1, store: "Shop 5" },
      { id: 48, name: "Product 48", price: 45, quantity: 1, store: "Shop 5" },
      { id: 49, name: "Product 49", price: 50, quantity: 1, store: "Shop 5" },
      { id: 40, name: "Product 40", price: 55, quantity: 1, store: "Shop 5" },
    ],
  },
  {
    id: 6,
    name: "Shop 6",
    products: [
      { id: 51, name: "Product 51", price: 10, quantity: 1, store: "Shop 6" },
      { id: 52, name: "Product 52", price: 15, quantity: 1, store: "Shop 6" },
      { id: 53, name: "Product 53", price: 20, quantity: 1, store: "Shop 6" },
      { id: 54, name: "Product 54", price: 25, quantity: 1, store: "Shop 6" },
      { id: 55, name: "Product 55", price: 30, quantity: 1, store: "Shop 6" },
      { id: 56, name: "Product 56", price: 35, quantity: 1, store: "Shop 6" },
      { id: 57, name: "Product 57", price: 40, quantity: 1, store: "Shop 6" },
      { id: 58, name: "Product 58", price: 45, quantity: 1, store: "Shop 6" },
      { id: 59, name: "Product 59", price: 50, quantity: 1, store: "Shop 6" },
      { id: 50, name: "Product 50", price: 55, quantity: 1, store: "Shop 6" },
    ],
  },
];
